name: darling_assistant
description: "A voice-controlled personal assistant app with natural lady voice interface"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  speech_to_text: ^6.4.1
  flutter_tts: ^3.8.5
  flutter_local_notifications: ^16.2.0
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.19.0
  provider: ^6.1.1
  http: ^1.1.2
  flutter_animate: ^4.3.0
  permission_handler: ^11.1.0
  flutter_markdown: ^0.6.18
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/sounds/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
